set(CPACK_GENERATOR ZIP)
set(CPACK_PACKAGE_NAME @CMAKE_PROJECT_NAME@)
set(CPACK_PACKAGE_VENDOR "Dmitry Khrykin")

set(CPACK_PACKAGE_VERSION @CMAKE_PROJECT_VERSION@)
set(CPACK_PACKAGE_VERSION_MAJOR @CMAKE_PROJECT_VERSION_MAJOR@)
set(CPACK_PACKAGE_VERSION_MINOR @CMAKE_PROJECT_VERSION_MINOR@)
set(CPACK_PACKAGE_VERSION_PATCH @CMAKE_PROJECT_VERSION_PATCH@)
set(CPACK_PACKAGE_VERSION_TWEAK @CMAKE_PROJECT_VERSION_TWEAK@)

set(CPACK_INSTALL_CMAKE_PROJECTS "@CMAKE_CURRENT_BINARY_DIR@;@CMAKE_PROJECT_NAME@;ALL;/")
set(CPACK_PACKAGE_DIRECTORY "@CMAKE_CURRENT_SOURCE_DIR@/packages")
set(CPACK_RESOURCE_FILE_LICENSE "@CMAKE_CURRENT_SOURCE_DIR@/LICENSE.txt")
set(CPACK_RESOURCE_FILE_README "PackageReadme.rtf")
set(CPACK_RESOURCE_FILE_WELCOME "@CMAKE_CURRENT_SOURCE_DIR@/deployment/Welcome.rtf")

set(CPACK_PACKAGE_DESCRIPTION_FILE "@CMAKE_CURRENT_SOURCE_DIR@/deployment/description.txt")
set(CPACK_COMPONENTS_ALL "Runtime")
set(CPACK_SYSTEM_NAME "@CMAKE_SYSTEM_NAME@")
set(CPACK_CMAKE_GENERATOR "@CMAKE_GENERATOR@")
set(CMAKE_GENERATOR_PLATFORM "@CMAKE_GENERATOR_PLATFORM@")

if (APPLE)
    set(CPACK_GENERATOR productbuild)

    set(CPACK_PRODUCTBUILD_IDENTITY_NAME "$ENV{CODESIGN_MAC_INSTALLER_IDENTITY}")
    set(CPACK_PKGBUILD_IDENTITY_NAME "${CPACK_PRODUCTBUILD_IDENTITY_NAME}")

    set(CPACK_PRODUCTBUILD_KEYCHAIN_PATH "$ENV{CODESIGN_KEYCHAIN}")
    set(CPACK_PKGBUILD_KEYCHAIN_PATH "${CPACK_PRODUCTBUILD_KEYCHAIN_PATH}")

    set(CPACK_SYSTEM_NAME "macOS")
    set(CPACK_PACKAGING_INSTALL_PREFIX /usr/local)
endif ()

if (WIN32)
    if ("@CMAKE_GENERATOR_PLATFORM@" STREQUAL "x64")
        set(CPACK_SYSTEM_NAME "win64")
    else ()
        set(CPACK_SYSTEM_NAME "win32")
    endif ()
endif ()

set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_SYSTEM_NAME}")